CREATE TABLE locale (
	locale_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	fallback_id INTEGER,
	title varchar(50) NOT NULL,
	localTitle varchar(50) NOT NULL,

	created_at TIMESTAMP DEFAULT NOW() NOT NULL,

	PRIMARY KEY (locale_id),
	FOREIGN KEY (fallback_id) REFERENCES locale (locale_id)
);
