create table shop (
	shop_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
	title VARCHAR(255) NOT NULL,
	latitude DOUBLE,
	longitude DOUBLE,

	PRIMARY KEY (shop_id),
--FOREIGN KEY (shop_id) REFERENCES entity (ent_id)
);
